/*
 *  Copyright (c) 2014, Lukas Tenbrink.
 *  * http://lukas.axxim.net
 */

// Date: 9-3-2014 13:41:43
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.psychedelicraft.client.render.blocks;

import net.minecraft.client.render.RenderLayers;
import net.minecraft.util.math.MathHelper;
import net.minecraft.client.model.*;

public class RiftJarContentModel extends Model<RiftJarBlockEntityRenderer.State> {
    private static final float INTERIOR_DILATION = 0.001F;
    private static final int MODEL_HEIGHT = 9;

    private final ModelPart base;
    private final ModelPart neck;
    private final ModelPart top;

    public RiftJarContentModel(ModelPart tree) {
        super(tree, RenderLayers::entityTranslucent);
        this.base = tree.getChild("base");
        this.neck = tree.getChild("neck");
        this.top = tree.getChild("top");
    }

    public static TexturedModelData createTexturedModelData() {
        ModelData data = new ModelData();
        ModelPartData root = data.getRoot();
        Dilation dilation = new Dilation(-INTERIOR_DILATION);
        root.addChild("base", ModelPartBuilder.create().cuboid(-4, 0, -4, 8, 5, 8, dilation), ModelTransform.NONE);
        root.addChild("neck", ModelPartBuilder.create().cuboid(-3, 5, -3, 6, 2, 6, dilation), ModelTransform.NONE);
        root.addChild("top", ModelPartBuilder.create().cuboid(-4, 7, -4, 8, 2, 8, dilation), ModelTransform.NONE);

        return TexturedModelData.of(data, 64, 32);
    }

    @Override
    public void setAngles(RiftJarBlockEntityRenderer.State state) {
        int fluidLevel = (int)(state.fillPercentage * MODEL_HEIGHT);
        updateLevelledCube(top, 7, 2, fluidLevel);
        updateLevelledCube(neck, 5, 2, fluidLevel);
        updateLevelledCube(base, 0, 5, fluidLevel);
    }

    private void updateLevelledCube(ModelPart part, int min, float height, int fluidLevel) {
        part.visible = fluidLevel > min;
        part.yScale = MathHelper.clamp((fluidLevel - min) / height, 0, 1);
    }
}
