/*
 *  Copyright (c) 2014, Lukas Tenbrink.
 *  * http://lukas.axxim.net
 */

// Date: 1-4-2013 15:05:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.psychedelicraft.client.rendering.blocks;

import ivorius.psychedelicraft.block.entity.BarrelBlockEntity;
import net.minecraft.client.model.*;
import net.minecraft.client.render.*;
import net.minecraft.client.util.math.MatrixStack;

/**
 * Updated by Sollace on 6 Jan 2023
 */
public class ModelBarrel extends Model {
    private final ModelPart tree;
    private final ModelPart tap3;

    public ModelBarrel(ModelPart tree) {
        super(RenderLayer::getEntityCutout);
        this.tree = tree;
        this.tap3 = tree.getChild("tap_3");
    }

    public static TexturedModelData getTexturedModelData() {
        ModelData data = new ModelData();
        ModelPartData root = data.getRoot();
        root.addChild("base", ModelPartBuilder.create().uv(0, 0).mirrored().cuboid(-4, -4, 0, 8, 8, 14), ModelTransform.pivot(0, 15, -7));
        root.addChild("top", ModelPartBuilder.create().uv(45, 0).mirrored().cuboid(-4, -6, -1, 8, 2, 16), ModelTransform.pivot(0, 15, -7));
        root.addChild("bottom", ModelPartBuilder.create().uv(45, 19).mirrored().cuboid(-4, 4, -1, 8, 2, 16), ModelTransform.pivot(0, 15, -7));
        root.addChild("right", ModelPartBuilder.create().uv(45, 38).mirrored().cuboid(-6, -4, -1, 2, 8, 16), ModelTransform.pivot(0, 15, -7));
        root.addChild("left", ModelPartBuilder.create().uv(82, 38).mirrored().cuboid(4, -4, -1, 2, 8, 16), ModelTransform.pivot(0, 15, -7));
        root.addChild("corner_1", ModelPartBuilder.create().uv(0, 23).mirrored().cuboid(-4, -4, -1, 1, 1, 16), ModelTransform.pivot(0, 15, -7));
        root.addChild("corner_2", ModelPartBuilder.create().uv(0, 26).mirrored().cuboid(3, -4, -1, 1, 1, 16), ModelTransform.pivot(0, 15, -7));
        root.addChild("corner_3", ModelPartBuilder.create().uv(0, 28).mirrored().cuboid(-4, 3, -1, 1, 1, 16), ModelTransform.pivot(0, 15, -7));
        root.addChild("corner_4", ModelPartBuilder.create().uv(0, 30).mirrored().cuboid(3, 3, -1, 1, 1, 16), ModelTransform.pivot(0, 15, -7));

        root.addChild("rack_1", ModelPartBuilder.create().uv(94, 12).mirrored().cuboid(-5, 0, -1, 10, 4, 2), ModelTransform.of(0, 20.5F, -5, -0.1487144F, 0, 0));
        root.addChild("rack_2", ModelPartBuilder.create().uv(94, 19).mirrored().cuboid(-5, 0, 0, 10, 4, 2), ModelTransform.of(0, 20.5F, 4, 0.1487144F, 0, 0));

        root.addChild("rack_3", ModelPartBuilder.create().uv(94, 0).mirrored().cuboid(-1, 7, 2, 2, 1, 10), ModelTransform.pivot(0, 15, -7));
        root.addChild("tap_1", ModelPartBuilder.create().uv(0, 50).mirrored().cuboid(-0.5F, 2, -1.5F, 1, 1, 2), ModelTransform.pivot(0, 15, -7));
        root.addChild("tap_2", ModelPartBuilder.create().uv(7, 50).mirrored().cuboid(-0.5F, 1.8F, -2.5F, 1, 2, 1), ModelTransform.pivot(0, 15, -7));
        root.addChild("tap_3", ModelPartBuilder.create().uv(12, 50).mirrored().cuboid(-1.5F, -0.21F, -0.5F, 3, 0, 1), ModelTransform.pivot(0, 17, -9));
        return TexturedModelData.of(data, 128, 64);
    }

    public void setRotationAngles(BarrelBlockEntity entity) {
        tap3.yaw = entity.tapRotation;
    }

    @Override
    public void render(MatrixStack matrices, VertexConsumer vertices, int light, int overlay, float r, float g, float b, float a) {
        tree.render(matrices, vertices, light, overlay);
    }
}
